### ISSUE TITLE
Looking for `vips_image_write_to_memory`

### ISSUE THREAD

**Issue by hbertoduarte** [olxgroup-oss/libvips-rust-bindings#15]
I've noticed that the function `vips_image_write_to_memory` does not have a corresponding method implemented for `VipsImage`, like the one that can be found for `vips_image_write_to_buffer`.

Is there a specific reason for that?

**Comment by augustocdias** [comment]
It is either introduced in newer versions or at that time I wasn't sure how to handle freeing the result of the function...

Note: although I'm answering here, I don't work for the company that owns this repo anymore and I'm not sure if they assigned someone to look after it (I believe they didn't). I can check PR's but I unfortunately don't have time to implement myself.

**Comment by hbertoduarte** [comment]
Well, I've managed to work with the following:
```rust
pub fn image_write_to_memory(&self) -> Vec<u8> {
    unsafe {
        let mut buffer_buf_size: u64 = 0;
        let buffer_out = bindings::vips_image_write_to_memory(self.ctx, &mut buffer_buf_size);
        let buf = std::slice::from_raw_parts(buffer_out as *mut u8, buffer_buf_size as usize).to_vec();
        bindings::g_free(buffer_out);
        buf
    }
}
```
But, given that I have no experience with FFI, I'm not even sure what kind of problems this implementation could have.

**Comment by augustocdias** [comment]
I am no expert either, but it seems sound.

**Comment by hbertoduarte** [comment]
Seeing as #16 has been merged, I think this issue can be closed now.
