### ISSUE TITLE
How to add feature for libvips

### ISSUE THREAD

**Issue by zhaohuxing** [olxgroup-oss/libvips-rust-bindings#18]
I read this README.md, but I do not know how to add a feature for libvips. eg: modify what files, exec what scripts?

**Comment by zhaohuxing** [comment]
> I see `vips_resize` in bindings.rs and `resize` in ops.rs. I see `vips_image_get_string` in bindings.rs, but not in ops.rs. I want to add `image_get_string` to ops.rs. How can I automatically generate it?

> You don't implement anything in the ops because it is auto generated based on libvips introspection api. 

I don't understand, why `vips_resize` in libvips, generate `resize` in ops.rs but `vips_image_get_string` in libvips, `image_get_string`not exists in ops.rs ?

**Comment by augustocdias** [comment]
There's not relation between bindings and ops. Bindings is generated from bindgen and ops: 

> If you want to see what goes in the ops, just compile the c file in the generate folder and execute it. It will list all operations that goes into that module. You don't implement anything in the ops because it is auto generated based on libvips introspection api. To generate it, simply run the generate.sh script.

Refer to operations in the libvips docs and you'll understand what goes there.

get_string is a method from the VipsImage object and I hadn't implemented everything possible in there. Feel free to create a PR if need it.

**Comment by zhaohuxing** [comment]
---
