### ISSUE TITLE
Update to 8.13

### ISSUE THREAD

**Issue by Jacherr** [olxgroup-oss/libvips-rust-bindings#27]
This crate provides *almost* everything I need, but the currently published version does not support `rgba` (https://www.libvips.org/API/current/libvips-create.html#vips-text) on `TextOptions` (https://docs.rs/libvips/1.4.3/libvips/ops/struct.TextOptions.html) which I need for my use case. Is it possible to update the published version to latest in order to get this functionality?

**Comment by bassco** [comment]
#28 has been published that should address this
