### ISSUE TITLE
VipsImage::clone Segfaults

### ISSUE THREAD

**Issue by kayleg** [olxgroup-oss/libvips-rust-bindings#6]
Attempting to clone a valid image seg faults. 

`VipsImage::new_from_buffer(data, "")?.clone()`

My workaround is currently to save the image as a jpeg and then create a new image from the jpeg buffer again.

Environment:
- vips 8.10.0 (installed from brew)
- mac os 10.15.6
- rust 1.45.2 (stable)

**Comment by augustocdias** [comment]
I guess I made a mistake. There's no need to manually implement clone since raw pointers in rust already do it. 


I'll change to your suggestion and release a new version on Monday (feel free to open a PR if you want)

**Comment by augustocdias** [comment]
I have published a new version with the fix.
